CREATE TABLE CUSTOMERS(
    CustomerID CHAR(5) PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Age INT CHECK (Age >= 0),

    CONSTRAINT chk_customerid CHECK (CHAR_LENGTH(CustomerID) = 5)
);
CREATE TABLE Orders (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    OrderDate DATE DEFAULT CURRENT_DATE,
    CustomerID CHAR(5) NOT NULL,
    Total_Price DECIMAL(10, 2) NOT NULL,

    CONSTRAINT uq_CustomerID FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);